main: staff.core.plugin.Main
name: StaffCore
version: 1.1.2
author: Warvale
description: Staff core plugin for Warvale
commands:
  sc:
    description: Test if the core of the plugin is functioning.
    usage: /sc
