main: staff.core.plugin.StaffCore
name: StaffCore
version: 1.1.2
author: Warvale
description: Staff core plugin for Warvale
commands:
  sc:
    description: Use staff chat.
    usage: /s
  globalmute:
    description: Mute the chat.
    usage: /globalmute