name: Staffcore
main: me.warvale.staffcore.StaffCore
version: ${project.version}
authors: [Aerh, Laep]
commands:
  ban:
    description: Ban command.
  kick:
    description: Kick command.
  s:
    description: Staff chat.
    aliases: [staffchat]
  gmute:
    description: Global mute for whole chat.
  warn:
    description: Warns a player.
  ip:
    description: Checks the IP of a player.
  tp:
    description: Teleport command.