name: StaffCore
main: net.warvale.staffcore.StaffCore
version: 1.0.0
authors: Warvale
commands:
  ban:
    description: Ban command.
  kick:
    description: Kick command.
  sc:
    description: Staff chat.
    aliases: [staffchat]
  gmute:
    description: Global mute for whole chat.
  ip:
    description: Displays the IP of a user.
  check:
    description: Check a player's history.
  tp:
    description: Teleport command.
  alert:
    description: Broadcast a message to the server.
  rank:
    description: Manages the ranks.

permissions:
  warvale.*:
    description: Gives access to all Rank commands.
    children:
      warvale.management: true
      warvale.staff: true
      warvale.punish: true
  warvale.management:
    description: Rank Management
    default: false
  warvale.staff:
    description: Allows your to access
    default: false
    children:
      warvale.punish: true
  warvale.punish:
    description: Allows you to punish other users
    default: op