name: StaffCore
main: me.warvale.staffcore.StaffCore
version: 1.0.0
authors: [Aerh, Laep]
commands:
  ban:
    description: Ban command.
  kick:
    description: Kick command.
  s:
    description: Staff chat.
    aliases: [staffchat]
  gmute:
    description: Global mute for whole chat.
  tp:
    description: Teleport command.
  alert:
    description: Broadcast a message.