name: ${project.name}
main: me.warvale.staffcore.StaffCore
version: ${project.version}
authors: [Aerh, Laep]
commands:
  ban:
    description: Ban command.
  kick:
    description: Kick command.
  s:
    description: Staff chat.
    aliases: [staffchat]
  gmute:
    description: Global mute.
  tp:
    description: Teleport command.