main: warvale.core.plugin.Main
name: CTFCore
version: 1.1.2
author: Pixelific
description: A CTF plugin.
commands:
  ctf:
    description: Test if the core of the plugin is functioning.
    usage: /ctf

  join:
    description: Join the game.
    usage: /join
  
  leave:
    description: Leave the game.
    usage: /leave
    
  start:
    description: Automatically start the game.
    usage: /start
  
  kit:
    description: Select a kit.
    usage: /kit 
  
  kits:
    description: List all kits.
    usage: /kits
